apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: servicemonitor
  serviceMonitorNamespaceSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 600Mi
    requests:
      cpu: 100m
      memory: 400Mi
  externalUrl: /prometheus
  routePrefix: /
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 5Gi
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ui-ing
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /prometheus
        backend:
          serviceName: prometheus-operated
          servicePort: 9090
