apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-cluster
spec:
  version: 5.0.3-v1
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
  terminationPolicy: Pause
  updateStrategy:
    type: RollingUpdate
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: default
      labels:
        app: servicemonitor
      interval: 10s
